name: WePhoto
description: A sample Polymer application
dependencies:
    polymer: ">=0.12.0 <0.13.0"
    core_elements: ">=0.1.0 <0.2.0"
    paper_elements: ">=0.1.0 <0.2.0" 
    google_drive_v2_api: ">=0.4.0 <0.5.0"
    google_oauth2_client: ">=0.3.4 <0.4.0"
transformers:
- polymer:
    entry_points:
    - web/wephoto.html
    - web/index.html
